### PR TITLE
Dung da them ten minh vao day

### PR DESCRIPTION
**Pull request by NguyenThuyDung14**

### CODE REVIEW

**Comment by DinhTienLen** [comment]
[Album](https://trello.com/c/nuBvDFS5/5-album)

**Comment by DinhTienLen** [comment]
[Login](https://trello.com/c/PvXpfh3a/3-login)

**Comment by DinhTienLen** [comment]
[Create Database](https://trello.com/c/IBfTiWgf/2-create-database)

**Comment by NguyenThuyDung14** [comment]
[Login](https://trello.com/c/PvXpfh3a/3-login)

**Pull request merged**
